### ISSUE TITLE
Hi would you provide the model such as netG_A2B.pth and so on?

### ISSUE THREAD

**Issue by leilaShen** [xw-hu/Mask-ShadowGAN#1]
Hi  xiaowei,
      would you provide the trained model files?  I've trained on USR_dataset, but since I'm not so familar with tuning the net,  the result seems should be better.
      Thanks a lot!

**Comment by xw-hu** [comment]
Since there are lots of different training sets, you can directly train the models by running "train_Mask-ShadowGAN".
