### ISSUE TITLE
Bad results

### ISSUE THREAD

**Issue by SkyeLu** [xw-hu/Mask-ShadowGAN#4]
Hi xiaowei,
Thanks for sharing your code! I trained the model using your code and got many unpleasant results. I wonder if it is due to the algorithm itself or some other reasons like training tricks? 

Examples(shadow to shadow-free):
![USR_shadow_0015](https://user-images.githubusercontent.com/31540747/69410318-b6dc0b00-0d45-11ea-9049-fc6eed5d53cd.jpg)
![USR_shadow_0015](https://user-images.githubusercontent.com/31540747/69410329-bf344600-0d45-11ea-9e39-84fb461c28ad.jpg)
![USR_shadow_0072](https://user-images.githubusercontent.com/31540747/69410342-c9eedb00-0d45-11ea-959a-dee1342976f2.jpg)
![USR_shadow_0072](https://user-images.githubusercontent.com/31540747/69410349-ceb38f00-0d45-11ea-9d35-c48ec283231c.jpg)

(shadow-free to shadow):
![USR_shadow_free_0014](https://user-images.githubusercontent.com/31540747/69410491-23efa080-0d46-11ea-9af9-24176193ea76.jpg)
![USR_shadow_free_0014](https://user-images.githubusercontent.com/31540747/69410500-29e58180-0d46-11ea-9979-64ea7b51e29d.jpg)

**Comment by xw-hu** [comment]
Yes. It may produce some bad results if the training images of such kind of scenes are limited. You can train the model on the training sets of SRD and ISTD and test the model on the testing sets of SRD and ISTD to have a quantitative evaluation and see whether the training procedure is right or not.

**Comment by naoto0804** [comment]
I got similar results when I trained the model on USR dataset.
Is it possible for you to share the `netG_A2B.pth` trained on USR dataset?
