### ISSUE TITLE
Evaluation code wanted

### ISSUE THREAD

**Issue by Roujack** [xw-hu/Mask-ShadowGAN#5]
Hi, thanks for the sharing of this project. I've trained the MaskShadowGAN on ISTD dataset. Just following the setting, I evaluate the result using RMSE metric on LAB color space(using my own code). The result is 8.87, which is far from 7.61 as reported in the paper. Could you please upload the code that you used for evaluation? I want to figure out what is wrong on my experiment. Thanks!

**Comment by xw-hu** [comment]
See your QQ email.

**Comment by evanlym** [comment]
Hi, thanks for sharing. Could you also please send the evaluation code to me at evanlym@outlook.com? Thanks a lot!

**Comment by Amy-214** [comment]
Could you also please send the evaluation code to me at zhangmy_2000@163.com? Thanks a lot!
