### ISSUE TITLE
Can not reproduce the same results

### ISSUE THREAD

**Issue by sophia303v** [xw-hu/Mask-ShadowGAN#6]
Hi, I have trained the Mask shadow Gan on ISTD dataset following the given setting too. But I can’t reproduce the result on the paper either. My result is 9.52 (rmse value on LAB color space). I would like to perform some academic experiments comparing with my own results. I wonder whether I make any mistakes during my evaluation. Would you mind sharing your evaluation code or the parameter setting on ISTD dataset? Thanks a lot!!

**Comment by xw-hu** [comment]
The parameter setting is the same as the public code. Please give me your email for the evaluation code.

**Comment by sophia303v** [comment]
Thank you so much for your response! My email is sophia303v@gmail.com.

**Comment by naoto0804** [comment]
I also have trained the MaskedShadowGAN on USR dataset following the instruction too. Furthermore, I used the evaluation code above. However, the result is 9.69 (in the paper, it is 7.61). If possible, could you share the model trained on USR dataset, to make sure I'm doing, @xw-hu? 

@sophia303v : were you able to reproduce the results?

**Comment by XiaMoooo** [comment]
Hi, I encountered the same problem. I have trained the Mask shadow Gan on ISTD dataset following the given setting too. But my result is 10.153. Would you mind sharing your evaluation code? My email: fj031717xiamo@163.com .Thanks a lot!!
